### ISSUE TITLE
Environment: Develop application in UAT

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow-feedback#31] opened 2016-11-21 20:42 UTC
As a Product Owneer, I would like to have the UAT environment accessible only on the VA network so that testing can occur and no one can access it outside of the VA network.

Acceptance Criteria
1.  Verify that Caseflow Feedback is in the UAT environment on the VA network only.

### Sub-Tasks

- [ ] QA discovery and scripting - validate url can be accessed

**Comment by shanear** [comment] 2016-12-09 21:33
This is a duplicate of https://github.com/department-of-veterans-affairs/appeals-deployment/issues/213. closing

**Closed as completed by shanear** 2016-12-09 21:33 UTC
